In [1]:
import numpy as np
import pandas as pd
import os
import pdb
import json

np.random.seed(97)

In [2]:
# load config
config_path = "./config.json"

config = json.load(open(config_path, "r"))
config

{'data_config': {'data_path': '/clusterfs/nilah/aniketh/SpliceNinja/input_data/'}}

In [4]:
# read data
gene_counts = pd.read_csv(os.path.join(config["data_config"]["data_path"], "geneCounts.tab"), sep="\t", index_col=0)
gene_counts = gene_counts.rename({"X": "gene_id"}, axis=1)
gene_counts

,gene_id,alias,AA3,AA4,AA5,AA6,AA7,AA8,AA9,SF3B6,...,XAB2_r1,YBX1,YTHDC1,ZCRB1,ZMAT5,ZNF207,ZNF326,ZNF830,ZRSR1,ZRSR2
1,ENSG00000115128,SF3B6,15901,23124,15834,15197,18806,19008,15872,4357,...,36818,9756,10898,22081,17596,22189,16064,44317,18577,17977
2,ENSG00000100813,ACIN1,561,1709,889,1998,395,1013,1164,2164,...,2055,2053,1675,1400,2081,1909,2165,3008,1768,1886
3,ENSG00000160710,ADAR,2565,7496,5975,9369,2401,3580,8205,9265,...,7594,8414,6010,5311,5010,6459,7330,4538,9286,10539
4,ENSG00000197381,ADARB1,392,3314,1517,3005,572,448,1953,1683,...,1725,1930,2570,1691,847,1290,931,224,1307,1452
5,ENSG00000091542,ALKBH5,3149,2328,1017,1451,1040,2321,1604,5726,...,3604,4537,4205,1698,1199,1808,1500,1571,2065,1722
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11872,ENSG00000198886,MT-ND4,559643,633058,823449,680683,966575,766482,416041,702480,...,468141,515939,654744,494408,445405,326871,485493,828095,468650,473854
11873,ENSG00000198786,MT-ND5,85978,135791,148516,109215,128999,36076,58019,152011,...,158357,162910,157393,106706,97391,148712,107765,240126,88405,100828
11874,ENSG00000198695,MT-ND6,9574,17418,16845,10093,17868,9358,3557,16737,...,14128,17866,16040,15818,8949,10691,11934,40606,7560,9255
11875,ENSG00000198727,MT-CYB,485683,474261,645586,495629,941309,375956,334967,457025,...,555356,516049,625714,449034,338824,480659,368941,749614,394926,394082
11876,ENSG00000210196,MT-TP,1164,3116,1745,2257,954,1035,1287,5032,...,3584,3830,5108,3893,1829,1574,3280,7442,1444,1637

In [5]:
# format description is here - https://github.com/vastgroup/vast-tools?tab=readme-ov-file#combine-output-format
inclusion_levels_full = pd.read_csv(os.path.join(config["data_config"]["data_path"], "INCLUSION_LEVELS_FULL-Hs2331.tab"), sep="\t")

In [6]:
inclusion_levels_full

,EVENT,COORD,LENGTH,FullCO,COMPLEX,AA1_1,AA1_1-Q,AA2_1,AA2_1-Q,AA3_1,...,ZNF207_1,ZNF207_1-Q,ZNF326_1,ZNF326_1-Q,ZNF830_1,ZNF830_1-Q,ZRSR1_1,ZRSR1_1-Q,ZRSR2_1,ZRSR2_1-Q
GENE,,,,,,,,,,,,,,,,,,,,,
TSPAN6,HsaEX0067681,chrX:100636191-100636207,17,"chrX:100636608+100636793,100636191-100636207,1...",S,0.00,"SOK,SOK,SOK,Bn,S@0.00,688.00",0.0,"SOK,SOK,SOK,Bn,S@0.00,776.00",0.72,...,1.40,"SOK,SOK,SOK,B2,S@15.61,1099.39",0.73,"SOK,SOK,SOK,B1,S@12.20,1658.80",0.0,"SOK,SOK,SOK,Bn,S@0.00,972.00",0.96,"SOK,SOK,SOK,B2,S@15.64,1613.36",1.79,"SOK,SOK,SOK,B2,S@26.06,1429.94"
TNMD,HsaEX0066298,chrX:100599016-100599182,167,"chrX:100597657,100599016-100599182,100599508",S,NaN,"N,N,N,Bn,S@0,0",NaN,"N,N,N,Bn,S@0,0",NaN,...,NaN,"N,N,N,Bn,S@0,0",NaN,"N,N,N,Bn,S@0,0",NaN,"N,N,N,Bn,S@0,0",NaN,"N,N,N,Bn,S@0,0",NaN,"N,N,N,Bn,S@0,0"
DPM1,HsaEX6078702,chr20:50955186-50955285,100,"chr20:50958363,50955186-50955285,50948662",S,100.00,"SOK,SOK,SOK,OK,S@1986.00,0.00",100.0,"SOK,SOK,SOK,OK,S@2257.00,0.00",100.00,...,100.00,"SOK,SOK,SOK,OK,S@5354.00,0.00",100.00,"SOK,SOK,SOK,OK,S@4771.00,0.00",100.0,"SOK,SOK,SOK,OK,S@7931.00,0.00",100.00,"SOK,SOK,SOK,OK,S@5644.00,0.00",100.00,"SOK,SOK,SOK,OK,S@5013.00,0.00"
SCYL3,HsaEX0056692,chr1:169855796-169855857,62,"chr1:169859041,169855796-169855857+169855932+1...",S,26.15,"OK,OK,OK,Bl,S@10.72,30.28",0.0,"N,N,N,Bn,S@0.00,4.00",0.00,...,6.15,"OK,OK,OK,B1,S@4.24,64.76",29.23,"OK,OK,OK,OK,S@24.55,59.45",100.0,"OK,OK,OK,OK,S@89.00,0.00",0.00,"OK,OK,OK,Bn,S@0.00,48.00",20.00,"OK,OK,OK,B1,S@13.80,55.20"
SCYL3,HsaEX0056690,chr1:169864458-169864508,51,"chr1:169866896,169864369+169864458-169864508,1...",S,100.00,"LOW,LOW,LOW,OK,S@33.00,0.00",NaN,"N,N,N,Bn,S@0,0",100.00,...,100.00,"OK,OK,OK,OK,S@94.00,0.00",92.31,"SOK,SOK,SOK,OK,S@92.31,7.69",100.0,"OK,OK,OK,OK,S@53.00,0.00",76.67,"SOK,SOK,SOK,OK,S@81.27,24.73",100.00,"SOK,SOK,SOK,OK,S@178.00,0.00"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
KDM5D,HsaINT0085241,chrY:19708072-19708243,172,chrY:19708244-19708423=19707934-19708071:-,IR,NaN,"N,N,0.0=123,0=0=0,1@NaN,NaN",NaN,"N,N,0.0=123,0=0=0,1@NaN,NaN",NaN,...,NaN,"N,N,0.0=123,0=0=0,1@NaN,NaN",NaN,"N,N,0.0=123,0=0=0,1@NaN,NaN",NaN,"N,N,0.0=123,0=0=0,1@NaN,NaN",NaN,"N,N,0.0=123,0=0=0,1@NaN,NaN",NaN,"N,N,0.0=123,0=0=0,1@NaN,NaN"
KDM5D,HsaINT0085242,chrY:19707747-19707933,187,chrY:19707934-19708071=19707147-19707746:-,IR,0.00,"LOW,LOW,0.0=138,0=0=15.0,1@0,15",0.0,"N,N,0.0=138,0=0=1.0,1@0,1",0.00,...,0.00,"VLOW,VLOW,0.0=138,0=0=12.0,1@0,12",0.00,"VLOW,VLOW,0.0=138,0=0=10.0,1@0,10",NaN,"N,N,0.0=138,0=0=0,1@NaN,NaN",0.00,"N,N,0.0=138,0=0=1.0,1@0,1",0.00,"VLOW,VLOW,0.0=138,0=0=11.0,1@0,11"
KDM5D,HsaINT0085243,chrY:19706864-19707146,283,chrY:19707147-19707746=19706794-19706863:-,IR,NaN,"N,N,0.0=151,0=0=0,1@NaN,NaN",NaN,"N,N,0.0=151,0=0=0,1@NaN,NaN",NaN,...,NaN,"N,N,0.0=151,0=0=0,1@NaN,NaN",NaN,"N,N,0.0=151,0=0=0,1@NaN,NaN",NaN,"N,N,0.0=151,0=0=0,1@NaN,NaN",NaN,"N,N,0.0=151,0=0=0,1@NaN,NaN",NaN,"N,N,0.0=151,0=0=0,1@NaN,NaN"
KDM5D,HsaINT0085244,chrY:19706641-19706793,153,chrY:19706794-19706863=19706441-19706640:-,IR,NaN,"N,N,0.0=104,0=0=0,1@NaN,NaN",NaN,"N,N,0.0=104,0=0=0,1@NaN,NaN",NaN,...,NaN,"N,N,0.0=104,0=0=0,1@NaN,NaN",NaN,"N,N,0.0=104,0=0=0,1@NaN,NaN",NaN,"N,N,0.0=104,0=0=0,1@NaN,NaN",NaN,"N,N,0.0=104,0=0=0,1@NaN,NaN",NaN,"N,N,0.0=104,0=0=0,1@NaN,NaN"
KDM5D,HsaINT0085245,chrY:19706346-19706440,95,chrY:19706441-19706640=19705415-19706345:-,IR,NaN,"N,N,0.0=46,0=0=0,1@NaN,NaN",NaN,"N,N,0.0=46,0=0=0,1@NaN,NaN",NaN,...,NaN,"N,N,0.0=46,0=0=0,1@NaN,NaN",NaN,"N,N,0.0=46,0=0=0,1@NaN,NaN",NaN,"N,N,0.0=46,0=0=0,1@NaN,NaN",NaN,"N,N,0.0=46,0=0=0,1@NaN,NaN",NaN,"N,N,0.0=46,0=0=0,1@NaN,NaN"

In [8]:
inclusion_levels_full.iloc[0]["FullCO"]

'chrX:100636608+100636793,100636191-100636207,100635746'